### ISSUE TITLE
npm run start concern

### ISSUE THREAD

**Issue by tlee** [MajorLeagueBaseball/g5-component#10]
npm run serve & npm run build-js-full

Was this the intent?  Running the server in the background, then running the build-js-full?  Doing so creates some issues if anything happens with the build-js-full command.  It will exit, and leave you with no other way to kill the server, other than grepping for the process and killing it.

Wouldn't a logical and && operator make more sense here?  Isn't build-js-full a dependency of starting up?  I think it would be worthwhile to exit if there are failures there.

npm run build-js-full && npm run serve

At a minimum, I'd think the order should be switched, build first, serve second, to prevent ending up in a state where your uneasily able to kill the server.

**Comment by gbabula** [comment]
I think the original thinking was to do both concurrently to speed up the process.

The order of commands seems odd, but during my testing it was that order that appeared to have the best performance and start-up time.

I'm going to adjust this, which makes the most sense as you mentioned - I overlooked the fact that the build command can possibly fail and leave you hanging.

```
npm run build-js-full && npm run serve
```
