### ISSUE TITLE
style guide

### ISSUE THREAD

**Issue by kuhe** [MajorLeagueBaseball/g5-component#21]
__Style Guide__

* [ ] Enforce MLBAM engineering style guide
* [ ] Enforce `bam-eslint-config`
* [ ] Enforce use of lowercase for native literal or primitive types

---

@gbabula I know you and I have for the most part internalized the SDK style guide, but there are two items I'd argue for.

- allow or enforce use of lowercase for native literal or primitive types (?) https://github.com/jsdoc3/jsdoc/issues/1046#issuecomment-126477791 

This makes sense to me because literals/primitives are very slightly different from their `new` counterparts. 

Some reasoning: `true instanceof Boolean // false (!)`, `null`, `void` and `undefined` are all lowercase in the language.

```js
boolean true
number 1
object {}
number[] vs. Array<Number>
void (undefined)
function<return_type(...arg_types)> () => {}
```

- perhaps we could make optional or remove the annotations which are identical to the source code?

```js

/*
 *
 * @class A
 * @extends B
 * 
 */
class A extends B {

    /**
     * @method doSomething
     */
    doSomething() {}

}

``` 

Even now, not every type/function is annotated this completely.

**Comment by gbabula** [comment]
I'm fine with enforcing lowercase, as long as its the same in the entire library.

You linked to JSDoc above, are we moving to ESDoc, or is there a counter argument to stay with JSDoc?

**Comment by gbabula** [comment]
I updated this issue with some TODO's.

Ideally, I would like to enforce the MLBAM styleguide and ESLint config, we need to figure out a good way to do that since both list in our internal artifactory.

**Comment by aplikesbikes** [comment]
What is the argument against publishing our ESLint config to public `npm`? 

Lack of contributors?

**Comment by kuhe** [comment]
Although not specifically valuable, I don't know what our policies are with open sourcing stuff. Additional maintenance too.

**Comment by gbabula** [comment]
@itspolo thoughts? do we have official guidelines documented somewhere?

**Comment by gbabula** [comment]
@adampirani @kuhe lets revisit this, sounds like there is interest in publishing our ESLint configuration 👍

**Comment by adampirani** [comment]
Also @kuhe's RWB package 👍

**Comment by adampirani** [comment]
And the g5 generator, maybe with a config file where consumers can add artifactory information.

Was trying to figure out best approach there, maybe having teams fork from an open source version, with the intent of only updating the config, while keeping all else in sync with the canonical repo
